### ISSUE TITLE
crash and a bug related to gravity affected blocks.

### ISSUE THREAD

**Issue by femboy101** [Nibaru/More-Slabs-Stairs-and-Walls#53]
the game immediately crashes in fabric 1.21 when I place down gravity affected slabs. 
here is the error info for the crash

Description: Exception ticking world
java.lang.IllegalStateException: Entity class games.twinhead.moreslabsstairsandwalls.block.entity.FallingSlabBlockEntity has not defined synched data value 8
at net.minecraft.class_2945$class_9222.method_56911(class_2945.java:231)
at net.minecraft.class_1297.<init>(class_1297.java:310)
at net.minecraft.class_1540.<init>(class_1540.java:72)
at games.twinhead.moreslabsstairsandwalls.block.entity.FallingSlabBlockEntity.<init>(FallingSlabBlockEntity.java:56)
at games.twinhead.moreslabsstairsandwalls.block.entity.FallingSlabBlockEntity.spawnFromBlock(FallingSlabBlockEntity.java:68)
at games.twinhead.moreslabsstairsandwalls.block.falling.FallingSlab.method_9588(FallingSlab.java:64)
at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1149)
at net.minecraft.class_3218.method_14189(class_3218.java:759)
at net.minecraft.class_6757.method_39390(class_6757.java:215)
at net.minecraft.class_6757.method_39377(class_6757.java:98)
at net.minecraft.class_3218.method_18765(class_3218.java:339)
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
at net.minecraft.class_1132.method_3748(class_1132.java:114)
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
at java.base/java.lang.Thread.run(Unknown Source)

sorry if that error info is redundant or not enough information. I have zero coding knowledge so I have no Idea what of it you do and don't need.

also a bug with gravity affected stairs is that they always land rightside up.

**Comment by asternomical** [comment]
same thing is happening with my server , crashes it and then server goes offline.
