### ISSUE TITLE
Glass Resource pack causing crash 1.19.3

### ISSUE THREAD

**Issue by Nibaru** [Nibaru/More-Slabs-Stairs-and-Walls#7]
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'more_slabs_stairs_and_walls'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "in" is null
	at games.twinhead.moreslabsstairsandwalls.client.Client.copyGlassCompatibilityPackIfMissing(Client.java:107)
	at games.twinhead.moreslabsstairsandwalls.client.Client.onInitializeClient(Client.java:27)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

**Comment by FibreTTP** [comment]
Seems to be fixed with https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/commit/8aaa6f4a3d7ded7f3de50d8956402434c34681c4 in 2.4.0
